### ISSUE TITLE
bug: secretToken vs. staticToken expected behavior

### ISSUE THREAD

**Issue by dino-rodriguez** [interledgerjs/ilp-plugin-http#11]
I’m currently configuring the HTTP plugin to work between JS and Java, and noticed that `secretToken` and `staticToken` don't exhibit the same behavior, even though `secretToken` is supposed to be an alias according to a comment (while `secret` uses JWTs).

It seems that when `staticToken` is specified, it appends `BEARER` to the token, while it does not do this with `secretToken`. Is this a bug, or expected behavior?

**Comment by sharafian** [comment]
That's expected, and the staticToken should be used when possible. It's basically because we wanted to start prepending Bearer but we wanted it to be non-breaking so rather than changing the behavior of an existing field we added a new one. The implementation should know to strip off 'Bearer' and handle either one
